version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: "@types/node" # manually updated
        update-types:
          - "version-update:semver-major"
      - dependency-name: "cli-spinners" # requires node >= 18.20, but ggt supports >= 18.0
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@swc-node/register" # https://github.com/swc-project/swc-node/issues/772

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
