version: 2
updates:
  - directory: /
    open-pull-requests-limit: 15
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: daily
    ignore:
      # These use esm
      - dependency-name: clean-stack
      - dependency-name: execa
      - dependency-name: get-port
      - dependency-name: got
      - dependency-name: inquirer
      - dependency-name: "@types/inquirer"
      - dependency-name: p-map
      - dependency-name: p-queue
      - dependency-name: serialize-error
