version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
