version: 2
updates:
  - directory: /
    open-pull-requests-limit: 15
    package-ecosystem: npm
    versioning-strategy: increase
    rebase-strategy: auto
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "find-up"
        update-types:
          - "version-update:semver-major"
