name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: error-id
    attributes:
      label: Error ID
      description: The ID of the error that occurred.
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected the bug not to happen!
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Anything else?
      description: Anything that will give us more context about the issue you are encountering.
